version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    command: celery -A workers.tasks worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    depends_on:
      - redis
      